{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0411b4cb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'\n",
    "\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from tensorflow import keras\n",
    "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
    "from tensorflow.keras.applications.mobilenet import MobileNet\n",
    "from tensorflow.keras.layers import Dense, GlobalAveragePooling2D\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "from tensorflow.keras.utils import to_categorical\n",
    "\n",
    "# Define the path to your training data\n",
    "train_data_dir = 'train'\n",
    "\n",
    "# Define the image size\n",
    "img_width, img_height = 224, 224"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "4f6718b4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "2b5cd775",
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 369 images belonging to 371 classes.\n",
      "INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3', '/job:localhost/replica:0/task:0/device:GPU:4')\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n",
      "INFO:tensorflow:batch_all_reduce: 85 all-reduces with algorithm = nccl, num_packs = 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:batch_all_reduce: 85 all-reduces with algorithm = nccl, num_packs = 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:batch_all_reduce: 85 all-reduces with algorithm = nccl, num_packs = 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:batch_all_reduce: 85 all-reduces with algorithm = nccl, num_packs = 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "12/12 [==============================] - 66s 529ms/step - loss: 6.8220 - accuracy: 0.0000e+00\n",
      "Epoch 2/20\n",
      "12/12 [==============================] - 8s 653ms/step - loss: 5.8170 - accuracy: 0.0136\n",
      "Epoch 3/20\n",
      "12/12 [==============================] - 8s 629ms/step - loss: 5.3385 - accuracy: 0.0840\n",
      "Epoch 4/20\n",
      "12/12 [==============================] - 8s 628ms/step - loss: 4.5220 - accuracy: 0.1491\n",
      "Epoch 5/20\n",
      "12/12 [==============================] - 8s 614ms/step - loss: 3.5623 - accuracy: 0.3144\n",
      "Epoch 6/20\n",
      "12/12 [==============================] - 8s 624ms/step - loss: 2.6118 - accuracy: 0.5610\n",
      "Epoch 7/20\n",
      "12/12 [==============================] - 8s 618ms/step - loss: 1.7564 - accuracy: 0.7073\n",
      "Epoch 8/20\n",
      "12/12 [==============================] - 8s 625ms/step - loss: 1.0944 - accuracy: 0.8374\n",
      "Epoch 9/20\n",
      "12/12 [==============================] - 8s 626ms/step - loss: 0.7045 - accuracy: 0.8753\n",
      "Epoch 10/20\n",
      "12/12 [==============================] - 8s 624ms/step - loss: 0.4447 - accuracy: 0.9621\n",
      "Epoch 11/20\n",
      "12/12 [==============================] - 8s 658ms/step - loss: 0.3985 - accuracy: 0.9458\n",
      "Epoch 12/20\n",
      "12/12 [==============================] - 8s 623ms/step - loss: 0.2650 - accuracy: 0.9783\n",
      "Epoch 13/20\n",
      "12/12 [==============================] - 8s 615ms/step - loss: 0.2468 - accuracy: 0.9621\n",
      "Epoch 14/20\n",
      "12/12 [==============================] - 8s 657ms/step - loss: 0.2185 - accuracy: 0.9648\n",
      "Epoch 15/20\n",
      "12/12 [==============================] - 8s 620ms/step - loss: 0.1293 - accuracy: 0.9919\n",
      "Epoch 16/20\n",
      "12/12 [==============================] - 8s 618ms/step - loss: 0.1707 - accuracy: 0.9729\n",
      "Epoch 17/20\n",
      "12/12 [==============================] - 8s 649ms/step - loss: 0.2082 - accuracy: 0.9729\n",
      "Epoch 18/20\n",
      "12/12 [==============================] - 8s 614ms/step - loss: 0.2209 - accuracy: 0.9648\n",
      "Epoch 19/20\n",
      "12/12 [==============================] - 8s 627ms/step - loss: 0.2277 - accuracy: 0.9566\n",
      "Epoch 20/20\n",
      "12/12 [==============================] - 8s 620ms/step - loss: 0.2214 - accuracy: 0.9593\n",
      "Found 10 images belonging to 10 classes.\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\n6 root error(s) found.\n  (0) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[cond/output/_22/_124]]\n\t [[div_no_nan_1/_213]]\n\t [[cond/output/_23/_128]]\n  (1) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[cond/output/_22/_124]]\n\t [[div_no_nan_1/_213]]\n  (2) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[cond/output/_22/_124]]\n  (3) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n  (4) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n  (5) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_test_function_81489]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[34], line 64\u001b[0m\n\u001b[1;32m     56\u001b[0m test_data_dir \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtest\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m     57\u001b[0m test_generator \u001b[38;5;241m=\u001b[39m test_datagen\u001b[38;5;241m.\u001b[39mflow_from_directory(\n\u001b[1;32m     58\u001b[0m     test_data_dir,\n\u001b[1;32m     59\u001b[0m     target_size\u001b[38;5;241m=\u001b[39m(img_width, img_height),\n\u001b[1;32m     60\u001b[0m     batch_size\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m4\u001b[39m,\n\u001b[1;32m     61\u001b[0m     class_mode\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcategorical\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m     62\u001b[0m )\n\u001b[0;32m---> 64\u001b[0m loss, accuracy \u001b[38;5;241m=\u001b[39m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mevaluate\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtest_generator\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     65\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mLoss:\u001b[39m\u001b[38;5;124m'\u001b[39m, loss)\n\u001b[1;32m     66\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mAccuracy:\u001b[39m\u001b[38;5;124m'\u001b[39m, accuracy)\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:52\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     50\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     51\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 52\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     53\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     54\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     55\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits'\n6 root error(s) found.\n  (0) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[cond/output/_22/_124]]\n\t [[div_no_nan_1/_213]]\n\t [[cond/output/_23/_128]]\n  (1) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[cond/output/_22/_124]]\n\t [[div_no_nan_1/_213]]\n  (2) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[cond/output/_22/_124]]\n  (3) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n  (4) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n  (5) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_4/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_test_function_81489]"
     ]
    }
   ],
   "source": [
    "import os\n",
    "os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'\n",
    "\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from tensorflow import keras\n",
    "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
    "from tensorflow.keras.applications.mobilenet import MobileNet\n",
    "from tensorflow.keras.layers import Dense, GlobalAveragePooling2D\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "from tensorflow.keras.utils import to_categorical\n",
    "\n",
    "# Define the path to your training data\n",
    "train_data_dir = 'train2'\n",
    "\n",
    "# Define the image size\n",
    "img_width, img_height = 224, 224\n",
    "\n",
    "# Function to preprocess the images\n",
    "def preprocess_images(img):\n",
    "    img = img.astype('float32')\n",
    "    img /= 255.0\n",
    "    return img\n",
    "\n",
    "train_datagen = ImageDataGenerator(\n",
    "    rescale=1.0/255.0,\n",
    "    preprocessing_function=preprocess_images\n",
    ")\n",
    "train_generator = train_datagen.flow_from_directory(\n",
    "    train_data_dir,\n",
    "    target_size=(img_width, img_height),\n",
    "    batch_size=32,\n",
    "    class_mode='categorical'\n",
    ")\n",
    "mirrored_strategy = tf.distribute.MirroredStrategy(devices=[\"/gpu:0\",\"/gpu:1\",\"/gpu:2\",\"/gpu:3\",\"/gpu:4\"])\n",
    "\n",
    "# Создание модели внутри MirroredStrategy\n",
    "with mirrored_strategy.scope():\n",
    "    base_model = MobileNet(weights='imagenet', include_top=False, input_shape=(img_width, img_height, 3))\n",
    "# Add a global spatial average pooling layer\n",
    "    x = base_model.output\n",
    "    x = GlobalAveragePooling2D()(x)\n",
    "# Add a fully-connected layer\n",
    "    x = Dense(1024, activation='relu')(x)\n",
    "# Add an output layer with the number of classes\n",
    "    num_classes = len(train_generator.class_indices)\n",
    "    predictions = Dense(num_classes, activation='softmax')(x)\n",
    "# Create the model\n",
    "    model = Model(inputs=base_model.input, outputs=predictions)\n",
    "# Compile the model\n",
    "    model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])\n",
    "# Train the model\n",
    "model.fit(train_generator, epochs=20, verbose=1)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "5f2412aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Сохранение модели\n",
    "model.save('image_similarity_model.h5')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "228c1580",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"model\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " input_1 (InputLayer)        [(None, 224, 224, 3)]     0         \n",
      "                                                                 \n",
      " conv1 (Conv2D)              (None, 112, 112, 32)      864       \n",
      "                                                                 \n",
      " conv1_bn (BatchNormalizatio  (None, 112, 112, 32)     128       \n",
      " n)                                                              \n",
      "                                                                 \n",
      " conv1_relu (ReLU)           (None, 112, 112, 32)      0         \n",
      "                                                                 \n",
      " conv_dw_1 (DepthwiseConv2D)  (None, 112, 112, 32)     288       \n",
      "                                                                 \n",
      " conv_dw_1_bn (BatchNormaliz  (None, 112, 112, 32)     128       \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_dw_1_relu (ReLU)       (None, 112, 112, 32)      0         \n",
      "                                                                 \n",
      " conv_pw_1 (Conv2D)          (None, 112, 112, 64)      2048      \n",
      "                                                                 \n",
      " conv_pw_1_bn (BatchNormaliz  (None, 112, 112, 64)     256       \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_pw_1_relu (ReLU)       (None, 112, 112, 64)      0         \n",
      "                                                                 \n",
      " conv_pad_2 (ZeroPadding2D)  (None, 113, 113, 64)      0         \n",
      "                                                                 \n",
      " conv_dw_2 (DepthwiseConv2D)  (None, 56, 56, 64)       576       \n",
      "                                                                 \n",
      " conv_dw_2_bn (BatchNormaliz  (None, 56, 56, 64)       256       \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_dw_2_relu (ReLU)       (None, 56, 56, 64)        0         \n",
      "                                                                 \n",
      " conv_pw_2 (Conv2D)          (None, 56, 56, 128)       8192      \n",
      "                                                                 \n",
      " conv_pw_2_bn (BatchNormaliz  (None, 56, 56, 128)      512       \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_pw_2_relu (ReLU)       (None, 56, 56, 128)       0         \n",
      "                                                                 \n",
      " conv_dw_3 (DepthwiseConv2D)  (None, 56, 56, 128)      1152      \n",
      "                                                                 \n",
      " conv_dw_3_bn (BatchNormaliz  (None, 56, 56, 128)      512       \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_dw_3_relu (ReLU)       (None, 56, 56, 128)       0         \n",
      "                                                                 \n",
      " conv_pw_3 (Conv2D)          (None, 56, 56, 128)       16384     \n",
      "                                                                 \n",
      " conv_pw_3_bn (BatchNormaliz  (None, 56, 56, 128)      512       \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_pw_3_relu (ReLU)       (None, 56, 56, 128)       0         \n",
      "                                                                 \n",
      " conv_pad_4 (ZeroPadding2D)  (None, 57, 57, 128)       0         \n",
      "                                                                 \n",
      " conv_dw_4 (DepthwiseConv2D)  (None, 28, 28, 128)      1152      \n",
      "                                                                 \n",
      " conv_dw_4_bn (BatchNormaliz  (None, 28, 28, 128)      512       \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_dw_4_relu (ReLU)       (None, 28, 28, 128)       0         \n",
      "                                                                 \n",
      " conv_pw_4 (Conv2D)          (None, 28, 28, 256)       32768     \n",
      "                                                                 \n",
      " conv_pw_4_bn (BatchNormaliz  (None, 28, 28, 256)      1024      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_pw_4_relu (ReLU)       (None, 28, 28, 256)       0         \n",
      "                                                                 \n",
      " conv_dw_5 (DepthwiseConv2D)  (None, 28, 28, 256)      2304      \n",
      "                                                                 \n",
      " conv_dw_5_bn (BatchNormaliz  (None, 28, 28, 256)      1024      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_dw_5_relu (ReLU)       (None, 28, 28, 256)       0         \n",
      "                                                                 \n",
      " conv_pw_5 (Conv2D)          (None, 28, 28, 256)       65536     \n",
      "                                                                 \n",
      " conv_pw_5_bn (BatchNormaliz  (None, 28, 28, 256)      1024      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_pw_5_relu (ReLU)       (None, 28, 28, 256)       0         \n",
      "                                                                 \n",
      " conv_pad_6 (ZeroPadding2D)  (None, 29, 29, 256)       0         \n",
      "                                                                 \n",
      " conv_dw_6 (DepthwiseConv2D)  (None, 14, 14, 256)      2304      \n",
      "                                                                 \n",
      " conv_dw_6_bn (BatchNormaliz  (None, 14, 14, 256)      1024      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_dw_6_relu (ReLU)       (None, 14, 14, 256)       0         \n",
      "                                                                 \n",
      " conv_pw_6 (Conv2D)          (None, 14, 14, 512)       131072    \n",
      "                                                                 \n",
      " conv_pw_6_bn (BatchNormaliz  (None, 14, 14, 512)      2048      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_pw_6_relu (ReLU)       (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_dw_7 (DepthwiseConv2D)  (None, 14, 14, 512)      4608      \n",
      "                                                                 \n",
      " conv_dw_7_bn (BatchNormaliz  (None, 14, 14, 512)      2048      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_dw_7_relu (ReLU)       (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_pw_7 (Conv2D)          (None, 14, 14, 512)       262144    \n",
      "                                                                 \n",
      " conv_pw_7_bn (BatchNormaliz  (None, 14, 14, 512)      2048      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_pw_7_relu (ReLU)       (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_dw_8 (DepthwiseConv2D)  (None, 14, 14, 512)      4608      \n",
      "                                                                 \n",
      " conv_dw_8_bn (BatchNormaliz  (None, 14, 14, 512)      2048      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_dw_8_relu (ReLU)       (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_pw_8 (Conv2D)          (None, 14, 14, 512)       262144    \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                                                 \n",
      " conv_pw_8_bn (BatchNormaliz  (None, 14, 14, 512)      2048      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_pw_8_relu (ReLU)       (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_dw_9 (DepthwiseConv2D)  (None, 14, 14, 512)      4608      \n",
      "                                                                 \n",
      " conv_dw_9_bn (BatchNormaliz  (None, 14, 14, 512)      2048      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_dw_9_relu (ReLU)       (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_pw_9 (Conv2D)          (None, 14, 14, 512)       262144    \n",
      "                                                                 \n",
      " conv_pw_9_bn (BatchNormaliz  (None, 14, 14, 512)      2048      \n",
      " ation)                                                          \n",
      "                                                                 \n",
      " conv_pw_9_relu (ReLU)       (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_dw_10 (DepthwiseConv2D  (None, 14, 14, 512)      4608      \n",
      " )                                                               \n",
      "                                                                 \n",
      " conv_dw_10_bn (BatchNormali  (None, 14, 14, 512)      2048      \n",
      " zation)                                                         \n",
      "                                                                 \n",
      " conv_dw_10_relu (ReLU)      (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_pw_10 (Conv2D)         (None, 14, 14, 512)       262144    \n",
      "                                                                 \n",
      " conv_pw_10_bn (BatchNormali  (None, 14, 14, 512)      2048      \n",
      " zation)                                                         \n",
      "                                                                 \n",
      " conv_pw_10_relu (ReLU)      (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_dw_11 (DepthwiseConv2D  (None, 14, 14, 512)      4608      \n",
      " )                                                               \n",
      "                                                                 \n",
      " conv_dw_11_bn (BatchNormali  (None, 14, 14, 512)      2048      \n",
      " zation)                                                         \n",
      "                                                                 \n",
      " conv_dw_11_relu (ReLU)      (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_pw_11 (Conv2D)         (None, 14, 14, 512)       262144    \n",
      "                                                                 \n",
      " conv_pw_11_bn (BatchNormali  (None, 14, 14, 512)      2048      \n",
      " zation)                                                         \n",
      "                                                                 \n",
      " conv_pw_11_relu (ReLU)      (None, 14, 14, 512)       0         \n",
      "                                                                 \n",
      " conv_pad_12 (ZeroPadding2D)  (None, 15, 15, 512)      0         \n",
      "                                                                 \n",
      " conv_dw_12 (DepthwiseConv2D  (None, 7, 7, 512)        4608      \n",
      " )                                                               \n",
      "                                                                 \n",
      " conv_dw_12_bn (BatchNormali  (None, 7, 7, 512)        2048      \n",
      " zation)                                                         \n",
      "                                                                 \n",
      " conv_dw_12_relu (ReLU)      (None, 7, 7, 512)         0         \n",
      "                                                                 \n",
      " conv_pw_12 (Conv2D)         (None, 7, 7, 1024)        524288    \n",
      "                                                                 \n",
      " conv_pw_12_bn (BatchNormali  (None, 7, 7, 1024)       4096      \n",
      " zation)                                                         \n",
      "                                                                 \n",
      " conv_pw_12_relu (ReLU)      (None, 7, 7, 1024)        0         \n",
      "                                                                 \n",
      " conv_dw_13 (DepthwiseConv2D  (None, 7, 7, 1024)       9216      \n",
      " )                                                               \n",
      "                                                                 \n",
      " conv_dw_13_bn (BatchNormali  (None, 7, 7, 1024)       4096      \n",
      " zation)                                                         \n",
      "                                                                 \n",
      " conv_dw_13_relu (ReLU)      (None, 7, 7, 1024)        0         \n",
      "                                                                 \n",
      " conv_pw_13 (Conv2D)         (None, 7, 7, 1024)        1048576   \n",
      "                                                                 \n",
      " conv_pw_13_bn (BatchNormali  (None, 7, 7, 1024)       4096      \n",
      " zation)                                                         \n",
      "                                                                 \n",
      " conv_pw_13_relu (ReLU)      (None, 7, 7, 1024)        0         \n",
      "                                                                 \n",
      " global_average_pooling2d (G  (None, 1024)             0         \n",
      " lobalAveragePooling2D)                                          \n",
      "                                                                 \n",
      " dense (Dense)               (None, 1024)              1049600   \n",
      "                                                                 \n",
      " dense_1 (Dense)             (None, 371)               380275    \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 4,658,739\n",
      "Trainable params: 4,636,851\n",
      "Non-trainable params: 21,888\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "loaded_model = keras.models.load_model('image_similarity_model.h5')\n",
    "loaded_model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "8c3507f3",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "#!pip install pydot"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "e2375307",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.\n"
     ]
    }
   ],
   "source": [
    "from keras.utils.vis_utils import plot_model\n",
    "plot_model(loaded_model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "e289d8c3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 10 images belonging to 10 classes.\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\n6 root error(s) found.\n  (0) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[div_no_nan_1/_221]]\n\t [[group_deps/_253]]\n\t [[div_no_nan_1/_217]]\n  (1) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[div_no_nan_1/_221]]\n\t [[group_deps/_253]]\n  (2) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[div_no_nan_1/_221]]\n  (3) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n  (4) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n  (5) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_test_function_81489]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[44], line 9\u001b[0m\n\u001b[1;32m      1\u001b[0m test_data_dir \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtest\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m      2\u001b[0m test_generator \u001b[38;5;241m=\u001b[39m test_datagen\u001b[38;5;241m.\u001b[39mflow_from_directory(\n\u001b[1;32m      3\u001b[0m     test_data_dir,\n\u001b[1;32m      4\u001b[0m     target_size\u001b[38;5;241m=\u001b[39m(img_width, img_height),\n\u001b[1;32m      5\u001b[0m     batch_size\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m1\u001b[39m,\n\u001b[1;32m      6\u001b[0m     class_mode\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcategorical\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m      7\u001b[0m )\n\u001b[0;32m----> 9\u001b[0m loss, accuracy \u001b[38;5;241m=\u001b[39m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mevaluate\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtest_generator\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     10\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mLoss:\u001b[39m\u001b[38;5;124m'\u001b[39m, loss)\n\u001b[1;32m     11\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mAccuracy:\u001b[39m\u001b[38;5;124m'\u001b[39m, accuracy)\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:52\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     50\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     51\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 52\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     53\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     54\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     55\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\nDetected at node 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 937, in _bootstrap\n      self._bootstrap_inner()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n      self.run()\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1824, in run_step\n      outputs = model.test_step(data)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1790, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py\", line 1109, in compute_loss\n      return self.compiled_loss(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/losses.py\", line 1984, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/keras/backend.py\", line 5565, in categorical_crossentropy\n      return tf.nn.softmax_cross_entropy_with_logits(\nNode: 'replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits'\n6 root error(s) found.\n  (0) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[div_no_nan_1/_221]]\n\t [[group_deps/_253]]\n\t [[div_no_nan_1/_217]]\n  (1) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[div_no_nan_1/_221]]\n\t [[group_deps/_253]]\n  (2) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n\t [[div_no_nan_1/_221]]\n  (3) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n\t [[div_no_nan/ReadVariableOp_3/_170]]\n  (4) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n\t [[update_3/AssignAddVariableOp/_237]]\n  (5) INVALID_ARGUMENT:  logits and labels must be broadcastable: logits_size=[0,371] labels_size=[0,10]\n\t [[{{node replica_1/categorical_crossentropy/softmax_cross_entropy_with_logits}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_test_function_81489]"
     ]
    }
   ],
   "source": [
    "test_data_dir = 'test'\n",
    "test_generator = test_datagen.flow_from_directory(\n",
    "    test_data_dir,\n",
    "    target_size=(img_width, img_height),\n",
    "    batch_size=1,\n",
    "    class_mode='categorical'\n",
    ")\n",
    "\n",
    "loss, accuracy = model.evaluate(test_generator)\n",
    "print('Loss:', loss)\n",
    "print('Accuracy:', accuracy)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8d6c956f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!pip install opencv-python\n",
    "#!python --version"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "f536b62d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 369 images belonging to 371 classes.\n",
      "369/369 [==============================] - 7s 19ms/step - loss: 17.2858 - accuracy: 0.0054\n",
      "Loss: 17.28577423095703\n",
      "Accuracy: 0.00542005430907011\n"
     ]
    }
   ],
   "source": [
    "import keras\n",
    "from keras.preprocessing.image import ImageDataGenerator\n",
    "\n",
    "# Загрузка модели\n",
    "model = keras.models.load_model('image_similarity_model.h5')\n",
    "# Define the image size\n",
    "img_width, img_height = 224, 224\n",
    "\n",
    "# Function to preprocess the images\n",
    "def preprocess_images(img):\n",
    "    img = img.astype('float32')\n",
    "    img /= 255.0\n",
    "    return img\n",
    "# Создание генератора для тестовых данных\n",
    "test_datagen = ImageDataGenerator(\n",
    "    rescale=1.0/255.0,\n",
    "    preprocessing_function=preprocess_images\n",
    ")\n",
    "test_data_dir = 'train'\n",
    "test_generator = test_datagen.flow_from_directory(\n",
    "    test_data_dir,\n",
    "    target_size=(img_width, img_height),\n",
    "    batch_size=1,\n",
    "    class_mode='categorical'\n",
    ")\n",
    "\n",
    "# Оценка модели на тестовых данных\n",
    "loss, accuracy = model.evaluate(test_generator)\n",
    "print('Loss:', loss)\n",
    "print('Accuracy:', accuracy)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b352bd3b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
